In [1]:
import pandas as pd
import plotly.express as px

In [2]:
acc_data = pd.read_csv("acc_data.csv")
ecg_data = pd.read_csv("ecg_data.csv")

In [3]:
acc_data

Empty DataFrame
Columns: [time, t_wall, t_device_ns, x, y, z]
Index: []

In [4]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [5]:
ecg_data

         time        t_wall         t_device_ns    ecg
0    0.000000  1.775666e+09  599616718117201488   -106
1    0.007692  1.775666e+09  599616718117201488  31743
2    0.015385  1.775666e+09  599616718117201488     -1
3    0.023077  1.775666e+09  599616718117201488   -112
4    0.030769  1.775666e+09  599616718117201488 -24577
..        ...           ...                 ...    ...
104  0.800000  1.775666e+09  599616718117201488      0
105  0.807692  1.775666e+09  599616718117201488    106
106  0.815385  1.775666e+09  599616718117201488  13824
107  0.823077  1.775666e+09  599616718117201488      0
108  0.830769  1.775666e+09  599616718117201488     27

[109 rows x 4 columns]

In [6]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data")