In [1]:
import pandas as pd
import plotly.express as px

In [7]:
hr_data = pd.read_csv("hrtest.csv")
acc_data = pd.read_csv("acc_data.csv")
ecg_data = pd.read_csv("ecg_data.csv")

In [3]:
hr_data

        timestamp   hr
0    1.775139e+09   70
1    1.775139e+09   70
2    1.775139e+09   69
3    1.775139e+09   69
4    1.775139e+09   69
..            ...  ...
115  1.775139e+09  132
116  1.775139e+09  132
117  1.775139e+09  132
118  1.775139e+09  132
119  1.775139e+09  132

[120 rows x 2 columns]

In [4]:
px.line(hr_data, y = "hr")

In [5]:
acc_data

Empty DataFrame
Columns: [time, t_wall, t_device_ns, x, y, z]
Index: []

In [ ]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [8]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data")