In [7]:
import pandas as pd
import plotly.express as px

In [8]:
acc_data = pd.read_csv("voxel_acc_data2.csv")
ecg_data = pd.read_csv("voxel_ecg_data2.csv")

In [9]:
acc_data

           time        t_wall         t_device_ns    x    y    z
0      0.000000  1.775669e+09  599616027776812180 -415  502 -845
1      0.005000  1.775669e+09  599616027776812180 -413  504 -840
2      0.010000  1.775669e+09  599616027776812180 -408  503 -834
3      0.015000  1.775669e+09  599616027776812180 -399  507 -833
4      0.020000  1.775669e+09  599616027776812180 -389  505 -839
...         ...           ...                 ...  ...  ...  ...
6151  30.106891  1.775670e+09  599616057728703270 -380  535 -832
6152  30.111891  1.775670e+09  599616057728703270 -385  535 -834
6153  30.116891  1.775670e+09  599616057728703270 -385  530 -836
6154  30.121891  1.775670e+09  599616057728703270 -385  526 -835
6155  30.126891  1.775670e+09  599616057728703270 -392  531 -836

[6156 rows x 6 columns]

In [10]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [11]:
ecg_data

           time        t_wall         t_device_ns    ecg
0      0.000000  1.775669e+09  599616028220482888  -2450
1      0.007692  1.775669e+09  599616028220482888    927
2      0.015385  1.775669e+09  599616028220482888  10861
3      0.023077  1.775669e+09  599616028220482888  16578
4      0.030769  1.775669e+09  599616028220482888  18797
...         ...           ...                 ...    ...
3937  30.292043  1.775670e+09  599616057989449094   1739
3938  30.299735  1.775670e+09  599616057989449094  -4094
3939  30.307428  1.775670e+09  599616057989449094   4369
3940  30.315120  1.775670e+09  599616057989449094  -2590
3941  30.322812  1.775670e+09  599616057989449094   -995

[3942 rows x 4 columns]

In [13]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data (Voxel wet fur)")