In [1]:
import pandas as pd
import plotly.express as px

In [2]:
acc_data = pd.read_csv("acc_data_rblc1.csv")
ecg_data = pd.read_csv("ecg_data_rblc1.csv")

In [3]:
acc_data

           time        t_wall         t_device_ns    x   y    z
0      0.000000  1.775730e+09  599619245617681726 -752  36  649
1      0.005000  1.775730e+09  599619245617681726 -761  37  640
2      0.010000  1.775730e+09  599619245617681726 -762  36  641
3      0.015000  1.775730e+09  599619245617681726 -766  33  641
4      0.020000  1.775730e+09  599619245617681726 -766  30  644
...         ...           ...                 ...  ...  ..  ...
6151  30.100269  1.775730e+09  599619275562950406 -804   3  578
6152  30.105269  1.775730e+09  599619275562950406 -806   2  581
6153  30.110269  1.775730e+09  599619275562950406 -804   1  585
6154  30.115269  1.775730e+09  599619275562950406 -809   2  587
6155  30.120269  1.775730e+09  599619275562950406 -809   4  589

[6156 rows x 6 columns]

In [4]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [5]:
ecg_data

           time        t_wall         t_device_ns   ecg
0      0.000000  1.775730e+09  599619246136731884   464
1      0.007692  1.775730e+09  599619246136731884  1506
2      0.015385  1.775730e+09  599619246136731884  2246
3      0.023077  1.775730e+09  599619246136731884  2385
4      0.030769  1.775730e+09  599619246136731884  2551
...         ...           ...                 ...   ...
3937  30.288747  1.775730e+09  599619275902402148    96
3938  30.296440  1.775730e+09  599619275902402148    80
3939  30.304132  1.775730e+09  599619275902402148    53
3940  30.311824  1.775730e+09  599619275902402148     0
3941  30.319516  1.775730e+09  599619275902402148   -56

[3942 rows x 4 columns]

In [6]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data (RbLc)")

# SANDBOX

In [7]:
import yaml

In [34]:
from datetime import datetime as dt
experiment_id = "test"
timestamp = dt.now().strftime("%y%m%d_%H%M")
filename = f"{experiment_id}_{timestamp}"
filename

'test_260410_1427'

In [ ]:
configfile = "/Users/rblc/create/work/elte/ecg_imu/scripts/config.yaml"
with open(configfile, "r") as f:
        data = yaml.safe_load(f)

{'experiment_id': 'test',
 'duration': 30,
 'belt_1': {'name': 'Polar H10 E6B05E24',
  'uuid': 'FFDB0E1C-0262-9016-D154-4562DABCBE43',
  'mac_address': 'A0:9E:1A:E6:B0:5E',
  'heart_rate_service': '0000180d-0000-1000-8000-00805f9b34fb',
  'pmd_control': 'fb005c81-02e7-f387-1cad-8acd2d8df0c8',
  'pmd_data': 'fb005c82-02e7-f387-1cad-8acd2d8df0c8'}}

In [41]:
data["experiment_id"]

'test'

In [42]:
from datetime import datetime as dt
experiment_id = data["experiment_id"]
timestamp = dt.now().strftime("%y%m%d_%H%M")
filename = f"{experiment_id}_{timestamp}"
filename

'test_260410_1447'

In [48]:
def filename_generator() -> str:
    with open(configfile, "r") as f:
        data = yaml.safe_load(f)
        experiment_id = (data["experiment_id"])
        timestamp = dt.now().strftime("%y%m%d_%H%M")
        filename = f"{experiment_id}_{timestamp}"
        return filename

filename_generator()

'test_260410_1451'