In [1]:
import pandas as pd
import plotly.express as px

In [2]:
acc_data = pd.read_csv("acc_data_vox_mozgas.csv")
ecg_data = pd.read_csv("ecg_data_vox_mozgas.csv")

In [3]:
acc_data

             time        t_wall         t_device_ns    x    y    z
0        0.000000  1.776081e+09  599616561120366666 -435 -591 -715
1        0.005000  1.776081e+09  599616561120366666 -440 -588 -718
2        0.010000  1.776081e+09  599616561120366666 -445 -589 -717
3        0.015000  1.776081e+09  599616561120366666 -458 -587 -716
4        0.020000  1.776081e+09  599616561120366666 -462 -584 -717
...           ...           ...                 ...  ...  ...  ...
24547  120.114483  1.776082e+09  599616681079849664 -376 -789 -487
24548  120.119483  1.776082e+09  599616681079849664 -376 -785 -488
24549  120.124483  1.776082e+09  599616681079849664 -376 -785 -492
24550  120.129483  1.776082e+09  599616681079849664 -378 -787 -486
24551  120.134483  1.776082e+09  599616681079849664 -373 -786 -493

[24552 rows x 6 columns]

In [4]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [5]:
ecg_data

             time        t_wall         t_device_ns   ecg
0        0.000000  1.776081e+09  599616561584118212  7114
1        0.007692  1.776081e+09  599616561584118212  6485
2        0.015385  1.776081e+09  599616561584118212  7180
3        0.023077  1.776081e+09  599616561584118212  7084
4        0.030769  1.776081e+09  599616561584118212  6547
...           ...           ...                 ...   ...
15617  120.161053  1.776082e+09  599616681222094086   -43
15618  120.168745  1.776082e+09  599616681222094086   -45
15619  120.176437  1.776082e+09  599616681222094086   -41
15620  120.184130  1.776082e+09  599616681222094086   -43
15621  120.191822  1.776082e+09  599616681222094086   -38

[15622 rows x 4 columns]

In [6]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data (Vox + takony)")

# SANDBOX

In [7]:
import yaml

In [8]:
from datetime import datetime as dt
experiment_id = "test"
timestamp = dt.now().strftime("%y%m%d_%H%M")
filename = f"{experiment_id}_{timestamp}"
filename

'test_260413_1401'

In [9]:
configfile = "/Users/rblc/create/work/elte/ecg_imu/scripts/config.yaml"
with open(configfile, "r") as f:
        data = yaml.safe_load(f)

ScannerError: while scanning a simple key
  in "/Users/rblc/create/work/elte/ecg_imu/scripts/config.yaml", line 4, column 1
could not find expected ':'
  in "/Users/rblc/create/work/elte/ecg_imu/scripts/config.yaml", line 5, column 1

In [ ]:
data["experiment_id"]

In [ ]:
from datetime import datetime as dt
experiment_id = data["experiment_id"]
timestamp = dt.now().strftime("%y%m%d_%H%M")
filename = f"{experiment_id}_{timestamp}"
filename

In [ ]:
def config_reader(item):
    import yaml
    CONFIGPATH = "/Users/rblc/create/work/elte/ecg_imu/scripts/config.yaml"
    with open(CONFIGPATH, "r") as f:
        config_data = yaml.safe_load(f)
        return config_data[item]

In [ ]:
config_data = config_reader("experiment_id")
config_data

In [ ]:
def filename_generator() -> str:
    with open(configfile, "r") as f:
        data = yaml.safe_load(f)
        experiment_id = (data["experiment_id"])
        timestamp = dt.now().strftime("%y%m%d_%H%M")
        filename = f"{experiment_id}_{timestamp}"
        return filename

filename_generator()