In [1]:
import pandas as pd
import plotly.express as px

In [2]:
acc_data = pd.read_csv("acc_data_rblc1.csv")
ecg_data = pd.read_csv("ecg_data_rblc1.csv")

In [3]:
acc_data

          time        t_wall         t_device_ns    x   y    z
0     0.000000  1.775730e+09  599619098672229950 -798  42  604
1     0.005000  1.775730e+09  599619098672229950 -795  43  604
2     0.010000  1.775730e+09  599619098672229950 -798  41  604
3     0.015000  1.775730e+09  599619098672229950 -798  43  602
4     0.020000  1.775730e+09  599619098672229950 -799  43  604
...        ...           ...                 ...  ...  ..  ...
1039  5.088418  1.775730e+09  599619103605647788 -792  51  611
1040  5.093418  1.775730e+09  599619103605647788 -792  50  611
1041  5.098418  1.775730e+09  599619103605647788 -793  49  606
1042  5.103418  1.775730e+09  599619103605647788 -793  50  603
1043  5.108418  1.775730e+09  599619103605647788 -792  48  605

[1044 rows x 6 columns]

In [4]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [5]:
ecg_data

         time        t_wall         t_device_ns   ecg
0    0.000000  1.775730e+09  599619099175105588  2304
1    0.007692  1.775730e+09  599619099175105588  2520
2    0.015385  1.775730e+09  599619099175105588  2643
3    0.023077  1.775730e+09  599619099175105588  2892
4    0.030769  1.775730e+09  599619099175105588  2948
..        ...           ...                 ...   ...
652  5.016013  1.775730e+09  599619103668041842  -347
653  5.023705  1.775730e+09  599619103668041842  -340
654  5.031398  1.775730e+09  599619103668041842  -340
655  5.039090  1.775730e+09  599619103668041842  -331
656  5.046782  1.775730e+09  599619103668041842  -320

[657 rows x 4 columns]

In [ ]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data (RbLc)")