In [8]:
import pandas as pd
import plotly.express as px

In [9]:
hr_data = pd.read_csv("hrtest.csv")
acc_data = pd.read_csv("acc_data.csv")

In [10]:
hr_data

        timestamp  hr
0    1.773849e+09  78
1    1.773849e+09  78
2    1.773849e+09  79
3    1.773849e+09  79
4    1.773849e+09  79
..            ...  ..
115  1.773849e+09  81
116  1.773849e+09  82
117  1.773849e+09  82
118  1.773849e+09  82
119  1.773849e+09  82

[120 rows x 2 columns]

In [11]:
px.line(hr_data, y = "hr")

In [12]:
acc_data

         time        t_wall         t_device_ns    x   y    z
0    0.000000  1.775557e+09  599616524173749960 -920  49  405
1    0.005000  1.775557e+09  599616524173749960 -922  44  404
2    0.010000  1.775557e+09  599616524173749960 -922  44  410
3    0.015000  1.775557e+09  599616524173749960 -925  43  411
4    0.020000  1.775557e+09  599616524173749960 -925  46  409
..        ...           ...                 ...  ...  ..  ...
967  4.734592  1.775557e+09  599616528753342086 -672  24  207
968  4.739592  1.775557e+09  599616528753342086 -655  51  245
969  4.744592  1.775557e+09  599616528753342086 -649  72  271
970  4.749592  1.775557e+09  599616528753342086 -648  83  299
971  4.754592  1.775557e+09  599616528753342086 -660  83  366

[972 rows x 6 columns]

In [14]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")